services:
  mysql_db:
    image: mysql:8
    container_name: funds_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234 #you can change password for root
    ports:
      - "3306:3306"
    command: >
      --innodb_buffer_pool_size=4G
      --innodb_log_buffer_size=256M
      --innodb_flush_log_at_trx_commit=2
      --max_allowed_packet=256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - funds_db_mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    container_name: funds_phpmyadmin_container
    environment:
      PMA_HOST: mysql_db
    ports:
      - "8080:80"
    depends_on:
      - mysql_db
    volumes:
      - phpmyadmin_data:/var/www/html

volumes:
  funds_db_mysql:
  phpmyadmin_data: